# syntax=docker/dockerfile:1
FROM docker.io/library/golang:1.23-bookworm

ARG HUGO_VERSION=0.166.0
RUN curl -fsSL -o /tmp/hugo.tar.gz \
      "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz" && \
    tar -xzf /tmp/hugo.tar.gz -C /usr/local/bin hugo && \
    rm /tmp/hugo.tar.gz

WORKDIR /site

CMD ["bash"]
